--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Mar 01 2017 13:45
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'db_name'
--
USE [F17I4DABH2Gr9]
GO

--
-- Create Table    : 'Person'   
-- PersonID        :  
-- Fornavn         :  
-- Mellemnavn      :  
-- Efternavn       :  
-- PersonType      :  
--
CREATE TABLE Person (
    PersonID       BIGINT IDENTITY(1,1) NOT NULL,
    Fornavn        NVARCHAR(255) NOT NULL,
    Mellemnavn     NVARCHAR(255) NOT NULL,
    Efternavn      NVARCHAR(255) NOT NULL,
    PersonType     NVARCHAR(255) NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (PersonID))
GO

--
-- Create Table    : 'Adresse'   
-- AdresseID       :  
-- Vejnavn         :  
-- Husnummer       :  
-- Postnummer      :  
--
CREATE TABLE Adresse (
    AdresseID      BIGINT IDENTITY(1,1) NOT NULL,
    Vejnavn        NVARCHAR(255) NOT NULL,
    Husnummer      BIGINT NOT NULL,
    Postnummer     BIGINT NOT NULL,
CONSTRAINT pk_Adresse PRIMARY KEY CLUSTERED (AdresseID))
GO

--
-- Create Table    : 'Telefon'   
-- TelefonID       :  
-- TelefonType     :  
-- TelefonNummer   :  
-- PersonID        :  (references Person.PersonID)
--
CREATE TABLE Telefon (
    TelefonID      BIGINT IDENTITY(1,1) NOT NULL,
    TelefonType    NVARCHAR(255) NOT NULL,
    TelefonNummer  NVARCHAR(255) NOT NULL,
    PersonID       BIGINT NOT NULL,
CONSTRAINT pk_Telefon PRIMARY KEY CLUSTERED (TelefonID),
CONSTRAINT fk_Telefon FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'PersonAdresse'   
-- PersonID        :  (references Person.PersonID)
-- AdresseID       :  (references Adresse.AdresseID)
--
CREATE TABLE PersonAdresse (
    PersonID       BIGINT NOT NULL,
    AdresseID      BIGINT NOT NULL,
CONSTRAINT pk_PersonAdresse PRIMARY KEY CLUSTERED (PersonID,AdresseID),
CONSTRAINT fk_PersonAdresse FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_PersonAdresse2 FOREIGN KEY (AdresseID)
    REFERENCES Adresse (AdresseID)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON Person TO public
GO
GRANT ALL ON Adresse TO public
GO
GRANT ALL ON Telefon TO public
GO
GRANT ALL ON PersonAdresse TO public
GO